In [1]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
import jieba

In [3]:
sentence = "我喜歡閱讀書籍，也喜歡使用電腦來學習新的知識"

In [4]:
words = list(jieba.cut(sentence))
words

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\student\AppData\Local\Temp\jieba.cache
Loading model cost 0.376 seconds.
Prefix dict has been built successfully.


['我', '喜歡', '閱讀', '書籍', '，', '也', '喜歡', '使用', '電腦來', '學習', '新', '的', '知識']

In [5]:
words_array = np.array(words).reshape(-1, 1)
words_array

array([['我'],
       ['喜歡'],
       ['閱讀'],
       ['書籍'],
       ['，'],
       ['也'],
       ['喜歡'],
       ['使用'],
       ['電腦來'],
       ['學習'],
       ['新'],
       ['的'],
       ['知識']], dtype='<U3')

In [6]:
onehot_encoder = OneHotEncoder(sparse_output=False)

In [7]:
onehot_encoded = onehot_encoder.fit_transform(words_array)

In [8]:
onehot_encoder.categories_

[array(['也', '使用', '喜歡', '學習', '我', '新', '書籍', '的', '知識', '閱讀', '電腦來', '，'],
       dtype='<U3')]

In [11]:
onehot_encoded

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.]])

In [12]:
# 找出「我」的 One-Hot Encoding
print(onehot_encoded[0,:])

# 找出「閱讀」的 One-Hot Encoding
print(onehot_encoded[2,:])

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
